version: "3.8"

services:
  web:
    build: .
    container_name: unempty-desk-container
    image: unempty-desk
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "8080:8080"
    devices:
      - "/dev/video0:/dev/video0"
    working_dir: /app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
